
  export const clothes = [
    { title: "Jogger Rosa",
      brand: "Bershka",
      size:"xs",
      sizeComplete:"Extrachica (XS)",
      img:"/clothes/bershka/Image (18).jpg",
      price:"200",
      type:"bottom",
      imgSlider:[
        "/clothes/bershka/Image (18).jpg",
        "/clothes/bershka/Image (24).jpg",
        "/clothes/bershka/Image (23).jpg"],
    },
    { title: "Suéter cuello alto",
      brand: "C&A",
      size:"s",
      sizeComplete:"Chica (S)",
      img:"/clothes/ca/Image (19c).jpg",
      price:"200",
      type:"top",
      imgSlider:[
        "/clothes/ca/Image (19c).jpg",
        "/clothes/ca/Image (15c).jpg",
        "/clothes/ca/Image (14c).jpg"],
    },
    { title: "Chamarra Khaky",
      brand: "C&A",
      size:"xs",
      sizeComplete:"Extrachica (XS)",
      img:"/clothes/ca/Image (241).jpg",
      price:"250",
      type:"top",
      imgSlider:[
        "/clothes/ca/Image (241).jpg",
        "/clothes/ca/Image (242).jpg",
        "/clothes/ca/Image (243).jpg"],
    },
    { title: "Suéter Rayas",
      brand: "C&A",
      size:"s",
      sizeComplete:"Chica (S)",
      img:"/clothes/ca/Image (012).jpg",
      price:"90",
      type:"top",
      imgSlider:[
        "/clothes/ca/Image (012).jpg",
        "/clothes/ca/Image (013).jpg",
        "/clothes/ca/Image (014).jpg"],
    },
    { title: "Jogger Azul con Franjas Laterales",
      brand: "C&A",
      size:"xs",
      sizeComplete:"Extrachica (XS)",
      img:"/clothes/ca/Image (44).jpg",
      price:"200",
      type:"bottom",
      imgSlider:[
        "/clothes/ca/Image (44).jpg",
        "/clothes/ca/Image (43).jpg",
        "/clothes/ca/Image (42).jpg"],
    },
    { title: "Pantalón Mezclilla Azul Deslavado",
      brand: "C&A",
      size:"s",
      sizeComplete:"Chica (S)",
      img:"/clothes/ca/Image (14).jpg",
      price:"200",
      type:"bottom",
      imgSlider:[
        "/clothes/ca/Image (14).jpg",
        "/clothes/ca/Image (13).jpg",
        "/clothes/ca/Image (12).jpg"],
    },
    { title: "Camisa Caras",
      brand: "C&A",
      size:"xs",
      sizeComplete:"Chica (XS)",
      img:"/clothes/ca/Image (24).jpg",
      price:"200",
      type:"top",
      imgSlider:[
        "/clothes/ca/Image (24).jpg",
        "/clothes/ca/Image (23).jpg",
        "/clothes/ca/Image (22).jpg"],
    },
    { title: "Suéter orange",
      brand: "Cuidado con el perro",
      size:"s",
      sizeComplete:"Chica (S)",
      img:"/clothes/ccp/Image (a3).jpg",
      price:"200",
      type:"top",
      imgSlider:[
        "/clothes/ccp/Image (a3).jpg",
        "/clothes/ccp/Image (a2).jpg",
        "/clothes/ccp/Image (a1).jpg"],
    },
    { title: "Cárdigan punto",
      brand: "Cuidado con el perro",
      size:"xs",
      sizeComplete:"Extrachica (XS)",
      img:"/clothes/ccp/Image (b3).jpg",
      price:"200",
      type:"top",
      imgSlider:[
        "/clothes/ccp/Image (b3).jpg",
        "/clothes/ccp/Image (b2).jpg",
        "/clothes/ccp/Image (b1).jpg"],
    },
    { title: "Jogger Azul Nylon",
      brand: "Cuidado con el perro",
      size:"xs",
      sizeComplete:"Extrachica (XS)",
      img:"/clothes/ccp/Image (41).jpg",
      price:"150",
      type:"bottom",
      imgSlider:[
        "/clothes/ccp/Image (41).jpg",
        "/clothes/ccp/Image (40).jpg",
        "/clothes/ccp/Image (39).jpg"],
    },
    { title: "Camiseta manga larga Negra",
      brand: "Cuidado con el perro",
      size:"s",
      sizeComplete:"Chica (S)",
      img:"/clothes/ccp/Image (50).jpg",
      price:"100",
      type:"top",
      imgSlider:[
        "/clothes/ccp/Image (50).jpg",
        "/clothes/ccp/Image (49).jpg",
        "/clothes/ccp/Image (48).jpg"],
    },
    { title: "Suéter tejido Verde",
      brand: "Cuidado con el perro",
      size:"xs",
      sizeComplete:"Extrachica (XS)",
      img:"/clothes/ccp/Image (67).jpg",
      price:"200",
      type:"top",
      imgSlider:[
        "/clothes/ccp/Image (67).jpg",
        "/clothes/ccp/Image (66).jpg",
        "/clothes/ccp/Image (65).jpg"],
    },
    { title: "Chamarra Mezclilla Azul Clara",
      brand: "Cuidado con el perro",
      size:"xs",
      sizeComplete:"Extrachica (XS)",
      img:"/clothes/ccp/Image (73).jpg",
      price:"250",
      type:"top",
      imgSlider:[
        "/clothes/ccp/Image (73).jpg",
        "/clothes/ccp/Image (72).jpg",
        "/clothes/ccp/Image (71).jpg"],
    },
    { title: "Camisa rayas",
      brand: "Cuidado con el perro",
      size:"xs",
      sizeComplete:"Extrachica (XS)",
      img:"/clothes/ccp/Image (15).jpg",
      price:"200",
      type:"top",
      imgSlider:[
        "/clothes/ccp/Image (15).jpg",
        "/clothes/ccp/Image (14).jpg",
        "/clothes/ccp/Image (13).jpg"],
    },
    { title: "Cazadora Teddy",
      brand: "Forever 21",
      size:"xs",
      sizeComplete:"Extrachica (XS)",
      img:"/clothes/forever21/Image (30).jpg",
      price:"350",
      type:"top",
      imgSlider:[
        "/clothes/forever21/Image (30).jpg",
        "/clothes/forever21/Image (29).jpg",
        "/clothes/forever21/Image (28).jpg"],
    },
    { title: "Sobrecamisa con borreguillo interior",
      brand: "Forever 21",
      size:"xs",
      sizeComplete:"Extrachica (XS)",
      img:"/clothes/forever21/Image (27).jpg",
      price:"250",
      type:"top",
      imgSlider:[
        "/clothes/forever21/Image (27).jpg",
        "/clothes/forever21/Image (26).jpg",
        "/clothes/forever21/Image (25).jpg"],
    },
    { title: "Suéter cuello tortuga",
      brand: "H&M",
      size:"xs",
      sizeComplete:"Extrachica (XS)",
      img:"/clothes/hm/Image (25a).jpg",
      price:"200",
      type:"top",
      imgSlider:[
        "/clothes/hm/Image (25a).jpg",
        "/clothes/hm/Image (24a).jpg",
        "/clothes/hm/Image (23a).jpg"],
    },
    { title: "Jogger Mostaza",
      brand: "H&M",
      size:"xs",
      sizeComplete:"Extrachica (XS)",
      img:"/clothes/hm/Image (19).jpg",
      price:"200",
      type:"bottom",
      imgSlider:[
        "/clothes/hm/Image (19).jpg",
        "/clothes/hm/Image (26).jpg",
        "/clothes/hm/Image (1).jpg"],
    },
    { title: "Sobrecamisa Militar",
      brand: "H&M",
      size:"s",
      sizeComplete:"Chica (S)",
      img:"/clothes/hm/Image (76).jpg",
      price:"300",
      type:"top",
      imgSlider:[
        "/clothes/hm/Image (76).jpg",
        "/clothes/hm/Image (75).jpg",
        "/clothes/hm/Image (74).jpg"],
    },
    { title: "Pantalón Skiny Beige",
      brand: "Otro",
      size:"s",
      sizeComplete:"Chica (S)",
      img:"/clothes/otro/Image (8).jpg",
      price:"150",
      type:"bottom",
      imgSlider:[
        "/clothes/otro/Image (8).jpg",
        "/clothes/otro/Image (7).jpg",
        "/clothes/otro/Image (5).jpg"],
    },
    { title: "Cardigan Azul",
      brand: "Otro",
      size:"xs",
      sizeComplete:"Extrachica (XS)",
      img:"/clothes/otro/Image (021).jpg",
      price:"150",
      type:"top",
      imgSlider:[
        "/clothes/otro/Image (021).jpg",
        "/clothes/otro/Image (020).jpg",
        "/clothes/otro/Image (019).jpg"],
    },
    { title: "Pantalón Mezclilla Deslavado",
      brand: "Otro",
      size:"s",
      sizeComplete:"Chica (S)",
      img:"/clothes/otro/Image (22).jpg",
      price:"150",
      type:"bottom",
      imgSlider:[
        "/clothes/otro/Image (22).jpg",
        "/clothes/otro/Image (21).jpg",
        "/clothes/otro/Image (20).jpg"],
    },
    { title: "Pantalón Gabardina Azul Cuadros",
      brand: "Otro",
      size:"s",
      sizeComplete:"Chica (S)",
      img:"/clothes/otro/Image (27).jpg",
      price:"200",
      type:"bottom",
      imgSlider:[
        "/clothes/otro/Image (27).jpg",
        "/clothes/otro/Image (29).jpg",
        "/clothes/otro/Image (28).jpg"],
    },
    { title: "Pantalón Gabardina Azul Rayas",
      brand: "Otro",
      size:"s",
      sizeComplete:"Chica (S)",
      img:"/clothes/otro/Image (32).jpg",
      price:"200",
      type:"bottom",
      imgSlider:[
        "/clothes/otro/Image (32).jpg",
        "/clothes/otro/Image (31).jpg",
        "/clothes/otro/Image (30).jpg"],
    },
    { title: "Pantalón Gabardina Gris Cuadros",
      brand: "Otro",
      size:"s",
      sizeComplete:"Chica (S)",
      img:"/clothes/otro/Image (35).jpg",
      price:"200",
      type:"bottom",
      imgSlider:[
        "/clothes/otro/Image (35).jpg",
        "/clothes/otro/Image (34).jpg",
        "/clothes/otro/Image (33).jpg"],
    },
    { title: "Pantalón Gabardina Azul Cuadros",
      brand: "Otro",
      size:"s",
      sizeComplete:"Chica (S)",
      img:"/clothes/otro/Image (47).jpg",
      price:"200",
      type:"bottom",
      imgSlider:[
        "/clothes/otro/Image (47).jpg",
        "/clothes/otro/Image (46).jpg",
        "/clothes/otro/Image (45).jpg"],
    },
    { title: "Camiseta Transparencias Azul",
      brand: "Fango",
      size:"s",
      sizeComplete:"Chica (S)",
      img:"/clothes/otro/Image (57).jpg",
      price:"200",
      type:"top",
      imgSlider:[
        "/clothes/otro/Image (57).jpg",
        "/clothes/otro/Image (56).jpg",
        "/clothes/otro/Image (55).jpg"],
    },
    { title: "Camisa Transparencias Negra",
      brand: "Fango",
      size:"s",
      sizeComplete:"Chica (S)",
      img:"/clothes/otro/Image (61).jpg",
      price:"200",
      type:"top",
      imgSlider:[
        "/clothes/otro/Image (61).jpg",
        "/clothes/otro/Image (60).jpg",
        "/clothes/otro/Image (59).jpg"],
    },
    { title: "Chamarra Rosa",
      brand: "Otro",
      size:"s",
      sizeComplete:"Chica (S)",
      img:"/clothes/otro/Image (79).jpg",
      price:"300",
      type:"top",
      imgSlider:[
        "/clothes/otro/Image (79).jpg",
        "/clothes/otro/Image (78).jpg",
        "/clothes/otro/Image (77).jpg"],
    },
    { title: "Camisa blanca Transparencias",
      brand: "Fango",
      size:"m",
      sizeComplete:"Mediana (M)",
      img:"/clothes/otro/Image (133).jpg",
      price:"250",
      type:"top",
      imgSlider:[
        "/clothes/otro/Image (133).jpg",
        "/clothes/otro/Image (131).jpg",
        "/clothes/otro/Image (132).jpg"],
    },
    { title: "Camisa rayas",
      brand: "Otro",
      size:"xs",
      sizeComplete:"Extrachica (XS)",
      img:"/clothes/otro/Image (121).jpg",
      price:"150",
      type:"top",
      imgSlider:[
        "/clothes/otro/Image (121).jpg",
        "/clothes/otro/Image (120).jpg",
        "/clothes/otro/Image (119).jpg"],
    },
    { title: "Camisa estampado",
      brand: "Otro",
      size:"s",
      sizeComplete:"Chica (S)",
      img:"/clothes/otro/Image (12).jpg",
      price:"200",
      type:"top",
      imgSlider:[
        "/clothes/otro/Image (12).jpg",
        "/clothes/otro/Image (11).jpg",
        "/clothes/otro/Image (10).jpg"],
    },
    { title: "Pantalón Mezclilla Rotos",
      brand: "Pull and bear",
      size:"s",
      sizeComplete:"Chica (S)",
      img:"/clothes/pull/Image (17).jpg",
      price:"200",
      type:"bottom",
      imgSlider:[
        "/clothes/pull/Image (17).jpg",
        "/clothes/pull/Image (16).jpg",
        "/clothes/pull/Image (15).jpg"],
    },
    { title: "Camiseta Manga Larga Deslavados",
      brand: "Pull and bear",
      size:"xs",
      sizeComplete:"Extrachica (XS)",
      img:"/clothes/pull/Image (64).jpg",
      price:"200",
      type:"top",
      imgSlider:[
        "/clothes/pull/Image (64).jpg",
        "/clothes/pull/Image (63).jpg",
        "/clothes/pull/Image (62).jpg"],
    },
    { title: "Blazer Azul",
      brand: "Pull and bear",
      size:"xs",
      sizeComplete:"Extrachica (XS)",
      img:"/clothes/pull/Image (81).jpg",
      price:"350",
      type:"top",
      imgSlider:[
        "/clothes/pull/Image (81).jpg",
        "/clothes/pull/Image (80).jpg",
        "/clothes/pull/Image (82).jpg"],
    },
    { title: "Camisa degradados",
      brand: "Pull and bear",
      size:"xs",
      sizeComplete:"Extrachica (XS)",
      img:"/clothes/pull/Image (30).jpg",
      price:"200",
      type:"top",
      imgSlider:[
        "/clothes/pull/Image (30).jpg",
        "/clothes/pull/Image (29).jpg",
        "/clothes/pull/Image (28).jpg"],
    },
    { title: "Camisa lineas",
      brand: "Pull and bear",
      size:"xs",
      sizeComplete:"Extrachica (XS)",
      img:"/clothes/pull/Image (27).jpg",
      price:"200",
      type:"top",
      imgSlider:[
        "/clothes/pull/Image (27).jpg",
        "/clothes/pull/Image (26).jpg",
        "/clothes/pull/Image (25).jpg"],
    },
    { title: "Sudadera color block",
      brand: "Zara",
      size:"s",
      sizeComplete:"Chica (S)",
      img:"/clothes/zara/Image (34a).jpg",
      price:"200",
      type:"top",
      imgSlider:[
        "/clothes/zara/Image (34a).jpg",
        "/clothes/zara/Image (33a).jpg",
        "/clothes/zara/Image (32a).jpg"],
    },
    { title: "Suéter abstracto ligero",
      brand: "Zara",
      size:"s",
      sizeComplete:"Chica (S)",
      img:"/clothes/zara/Image (31a).jpg",
      price:"200",
      type:"top",
      imgSlider:[
        "/clothes/zara/Image (31a).jpg",
        "/clothes/zara/Image (30a).jpg",
        "/clothes/zara/Image (29a).jpg"],
    },
    { title: "Suéter punto",
      brand: "Zara",
      size:"s",
      sizeComplete:"Chica (S)",
      img:"/clothes/zara/Image (28z).jpg",
      price:"300",
      type:"top",
      imgSlider:[
        "/clothes/zara/Image (28z).jpg",
        "/clothes/zara/Image (27z).jpg",
        "/clothes/zara/Image (26a).jpg"],
    },
    { title: "Cardigan con cierre",
      brand: "Zara",
      size:"s",
      sizeComplete:"Chica (S)",
      img:"/clothes/zara/Image (33).jpg",
      price:"200",
      type:"top",
      imgSlider:[
        "/clothes/zara/Image (33).jpg",
        "/clothes/zara/Image (32).jpg",
        "/clothes/zara/Image (31).jpg"],
    },
    { title: "Pantalón Rotos",
      brand: "Zara",
      size:"s",
      sizeComplete:"Chica (S)",
      img:"/clothes/zara/Image (1).jpg",
      price:"300",
      type:"bottom",
      imgSlider:[
        "/clothes/zara/Image (1).jpg",
        "/clothes/zara/Image (3).jpg",
        "/clothes/zara/Image (2).jpg"],
    },
    { title: "Pantalón Mezclilla Rotos",
      brand: "Zara",
      size:"xg",
      sizeComplete:"ExtraGrande (XG)",
      img:"/clothes/zara/Image (38).jpg",
      price:"300",
      type:"bottom",
      imgSlider:[
        "/clothes/zara/Image (38).jpg",
        "/clothes/zara/Image (37).jpg",
        "/clothes/zara/Image (36).jpg"],
    },
    { title: "Sobrecamisa Mezclilla Clara",
      brand: "Zara",
      size:"s",
      sizeComplete:"Chica (S)",
      img:"/clothes/zara/Image (70).jpg",
      price:"250",
      type:"top",
      imgSlider:[
        "/clothes/zara/Image (70).jpg",
        "/clothes/zara/Image (69).jpg",
        "/clothes/zara/Image (68).jpg"],
    },
    { title: "Pantalón rayas Negro",
      brand: "Zara",
      size:"s",
      sizeComplete:"Chica (S)",
      img:"/clothes/zara/Image (11).jpg",
      price:"250",
      type:"bottom",
      imgSlider:[
        "/clothes/zara/Image (11).jpg",
        "/clothes/zara/Image (10).jpg",
        "/clothes/zara/Image (9).jpg"],
    },
    { title: "Camisa estampado",
      brand: "Zara",
      size:"s",
      sizeComplete:"Chica (S)",
      img:"/clothes/zara/Image (361).jpg",
      price:"250",
      type:"top",
      imgSlider:[
        "/clothes/zara/Image (361).jpg",
        "/clothes/zara/Image (35).jpg",
        "/clothes/zara/Image (34).jpg"],
    },
    { title: "Camisa letras",
      brand: "Zara",
      size:"s",
      sizeComplete:"Chica (S)",
      img:"/clothes/zara/Image (371).jpg",
      price:"250",
      type:"top",
      imgSlider:[
        "/clothes/zara/Image (371).jpg",
        "/clothes/zara/Image (381).jpg",
        "/clothes/zara/Image (39).jpg"],
    },
    { title: "Blazer Negro",
      brand: "Zara",
      size:"s",
      sizeComplete:"Chica (S)",
      img:"/clothes/zara/Image (6).jpg",
      price:"300",
      type:"top",
      imgSlider:[
        "/clothes/zara/Image (6).jpg",
        "/clothes/zara/Image (5).jpg",
        "/clothes/zara/Image (4).jpg"],
    },

  ];


  export const talla = [
    { title: "Talla (Todas)", value: "" },
    { title: "Extrachico (XS)", value: "xs" },
    { title: "Chico (S)", value: "s" },
    { title: "Mediana (M)", value: "m" },
    { title: "Grande (G)", value: "g" },
    { title: "Extragrande (XG)", value: "xg" },
  ];

  export const tipo = [
    { title: "Tipo (Todos)", value: "" },
    { title: "Top (Parte de arriba)", value: "top" },
    { title: "Bottom (Parte de abajo)", value: "bottom" },
  ];

  export const marca = [
    { title: "Marca (Todas)", value: "" },
    { title: "Bershka", value: "bershka" },
    { title: "C&A", value: "ca" },
    { title: "Cuidado con el perro", value: "cuidado con el perro" },
    { title: "Fango", value: "fango" },
    { title: "Forever 21", value: "forever 21" },
    { title: "H&M", value: "hm" },
    { title: "Otro", value: "otro" },
    { title: "Pull & Bear", value: "pull and bear" },
    { title: "Zara", value: "zara" },
  ];

  export const manufacturers =  [
    "Acura",
    "Alfa Romeo",]


  export const footerLinks = [
    {
      title: "Nuestras redes",
      links: [
        { title: "Instagram", url: "https://www.instagram.com/otd.bazar?igsh=MWJvc2Y4ODZyYzhudw%3D%3D&utm_source=qr" },
        { title: "Facebook", url: "https://www.facebook.com/share/CRhBqYjVjQD6bp1o/?mibextid=LQQJ4d" },
      ],
    },
  ];